name: Deploy handbook

on:
  push:
    branches: main
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Working directory check
        run: |
          pwd
          ls

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Verify dependencies
        run: |
          pandoc --version

      - name: Build
        run: pandoc --metadata-file ./config/default.yaml --toc --number-sections handbook.md -o graduate-handbook.pdf

      - name: Verify build
        run: ls graduate-handbook.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            graduate-handbook.pdf
